name: Build

on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - os: ubuntu-latest
          vcpkg_triplet: x64-linux-release
          build_type: Release
        - os: windows-latest
          vcpkg_triplet: x64-windows-release
          build_type: Release
    env:
      BUILD_TYPE: ${{ matrix.config.build_type }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Vcpkg Setup
      id: vcpkg
      uses: johnwason/vcpkg-action@v4
      with:
        manifest-dir: ${{ github.workspace }}
        triplet: ${{ matrix.config.vcpkg_triplet }}
        token: ${{ github.token }}
        cache-key: ${{ matrix.config.os }}
    - name: Build
      run: |
        cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
    - name: Upload artifacts (CI)
      uses: actions/upload-artifact@v2
      with:
        name: rctgen-${{ matrix.config.os }}-${{ env.BUILD_TYPE }}
        path: |
          ${{ github.workspace }}/build/${{ env.BUILD_TYPE }}
          !${{ github.workspace }}/build/${{ env.BUILD_TYPE }}/**/*.lib
          !${{ github.workspace }}/build/${{ env.BUILD_TYPE }}/**/*.pdb
        if-no-files-found: error
